name: Android CI Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout source
        uses: actions/checkout@v4

      # Setup JDK 17 (required for Gradle 9.x)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # Generate Gradle wrapper (fixes GradleWrapperMain error)
      - name: Generate Gradle wrapper
        run: gradle wrapper --gradle-version 9.1

      # Make gradlew executable
      - name: Make gradlew executable
        run: chmod +x gradlew

      # Build debug APK
      - name: Build with Gradle
        run: ./gradlew assembleDebug --stacktrace

      # Upload APK as artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: VCamera-Debug-APK
          path: app/build/outputs/apk/debug/*.apk
