name: Android CI Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo including submodules (like opensdk)
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # Set up JDK (Java 17 is safe for Android builds)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      # Grant execution permission for gradlew
      - name: Make gradlew executable
        run: chmod +x gradlew

      # Build Debug APK
      - name: Build Debug APK
        run: ./gradlew assembleDebug --stacktrace

      # Upload artifact (APK) so you can download it from Actions
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: VCamera-Debug
          path: app/build/outputs/apk/debug/*.apk
